<?php
$datas = [
    'addresses.com',
    'addresssearch.com',
    'advancedpeoplesearch.com',
    'allpeople.com',
    'americaphonebook.com',
    'anywho.com',
    'beenverified.com',
    'bumper.com',
    'callersmart.com',
    'checkpeople.com',
    'classmates.com',
    'cocofinder.com',
    'contacts411.com',
    'easypeoplesearch.com',
    'emailtracer.com',
    'fastpeoplesearch.com',
    'fastpeoplesearch.info',
    'fastpeoplesearch.io',
    'findpeoplefast.net',
    'findpeoplesearch.com',
    'freepeopledirectory.com',
    'freepeoplesearch.com',
    'freepeoplesearch.io',
    'gladIknow.com',
    'golookup.com',
    'goodsearch.com',
    'goreversephone.com',
    'greatpeoplesearch.com',
    'greypages.com',
    "backgroundchecks.com",
    "beenverified.com",
    "checkpeople.com",
    "familytreenow.com",
    "instantcheckmate.com",
    "intelius.com",
    "peoplefinders.com",
    "peekyou.com",
    "pipl.com",
    "radaris.com",
    "spokeo.com",
    "truthfinder.com",
    "whitepages.com",
    "arrestrecords.com",
    "courthousedirect.com",
    "criminalrecords.com",
    "offenderradar.com",
    "publicrecords.com",
    "recordsfinder.com",
    "recordspage.org",
    "searchbug.com",
    "searchpublicrecords.com",
    "searchquarry.com",
    "staterecords.org",
    "ussearch.com",
    "numlookup.com",
    "privatenumberchecker.com",
    "reversephonecheck.com",
    "revealname.com",
    "revealphoneowner.com",
    "spydialer.com",
    "usphonebook.com",
    "idcrawl.com",
    "idstrong.com",
    "idtrue.com",
    "kidslivesafe.com",
    "privateeye.com",
    "socialcatfish.com",
    "spyfly.com",
    "insideview.com",
    "leadcrunch.com",
    "leadiq.com",
    "leadjig.com",
    "leadloft.com",
    "rocketreach.co",
    "salesintel.io",
    "swordfish.ai",
    "missouriwarrantroundup.org",
    "newenglandfacts.com",
    "northcarolinawarrant.org",
    "notariescalifornia.com",
    "officialusa.com",
    "ohioarrestwarrant.org",
    "oldphonebook.com",
    "acxiom.com",
    "corelogic.com",
    "datatree.com",
    "epsilon.com",
    "experian.com",
    "i360.com",
    "inmarket.com",
    "lexisnexis.com",
    "ncsolutions.com",
    "truthfinder.com",
    "whitepages.com",
    "ussearch.com",
    "truepeoplesearch.com",
    "zabasearch.com",
    "thatsthem.com",
    "usatrace.com",
    "usapeoplesearch.com",
    "telephonedirectories.us",
    "texasarrests.org",
    "texasarrestwarrants.org",
    "valpak.com",
    "voilanorbert.com",
    "trustoria.com",
    // added from missing1 search sites (deduped)
    // "24counter.com",
    // "411.com",
    // "411.info",
    // "411locate.com",
    // "absolutepeoplesearch.com",
    // "address.us.com",
    // "allareacodes.com",
    // "arivify.com",
    // "callercenter.com",
    // "cellrevealer.com",
    // "centeda.com",
    // "homemetry.com",
    // "information.com",
    // "infotracer.com",
    // "lookify.io",
    // "mylife.com",
    // "neighbor.report",
    // "neighborwho.com",
    // "numberguru.com",
    // "nuwber.com",
    // "onlinesearches.com",
    // "ownerly.com",
    // "thisnumber.com",
    // "yellowbook.com",
    // "yellowpagesdirectory.com",
];
